  
name: Waka Readme

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    # Runs at every 5 minutes
    - cron: "5 * * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          API_BASE_URL: https://waka.hackclub.com/api
          WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
          SHOW_TITLE: true
          COMMIT_MESSAGE: changed code state
